apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  username: admin  # Replace with the Base64-encoded value of your new username
  password: password  # Replace with the Base64-encoded value of your new password