apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 32000  # Optional: Expose as NodePort to access externally
  type: NodePort  # Make the service accessible from outside the cluster