apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  username: YWRtaW4=  # Replace with your Base64 encoded username
  password: cGFzc3dvcmQ=  # Replace with your Base64 encoded password