apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          env:
            - name: MONGO_CONNECTION_STRING
              value: "mongodb://localhost:27017"  # Or the correct host/port of your local MongoDB
          ports:
            - containerPort: 27017